# Pod Disruption Budget - ensures availability during voluntary disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prism-api-pdb
  namespace: prism-ai
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: prism-api-server
