# Release Workflow
# Creates GitHub releases and publishes artifacts

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          # Generate changelog from git commits
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s (%h)" > CHANGELOG.md
          cat CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-binaries:
    name: Build Release Binaries
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binary
        run: |
          cargo build --release --bin api_server --features api_server --target ${{ matrix.target }}
        working-directory: 03-Source-Code

      - name: Package binary
        run: |
          cd 03-Source-Code/target/${{ matrix.target }}/release
          tar czf api_server-${{ github.ref_name }}-${{ matrix.target }}.tar.gz api_server
          sha256sum api_server-${{ github.ref_name }}-${{ matrix.target }}.tar.gz > api_server-${{ github.ref_name }}-${{ matrix.target }}.tar.gz.sha256

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            03-Source-Code/target/${{ matrix.target }}/release/api_server-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
            03-Source-Code/target/${{ matrix.target }}/release/api_server-${{ github.ref_name }}-${{ matrix.target }}.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
